### ISSUE TITLE
UDF execute is not working 

### ISSUE THREAD

**Issue by niechen** [aerospike/aql-java#3]
I first set lua path with `set LUA_USERPATH '/path/to/lua/files/'`. And then when I try to execute a UDF using `EXECUTE pkgname.funcname(arg1) ON namespace.setname`, this error is thrown:
```
Error on line: 1, Aerospike org.luaj.vm2.LuaError: aerospike:179 attempt to index ? (a nil value)
stack traceback:
    aerospike:179: in function <aerospike:157>
    [Java]: in ?
0 INFO  AQL  - Node BB9632727727902 172.31.22.99:3000 refresh failed: com.aerospike.client.AerospikeException$Parse: Error Code -2: Node name is empty
	at com.aerospike.client.cluster.Node.verifyNodeName(Node.java:111)
	at com.aerospike.client.cluster.Node.refresh(Node.java:91)
	at com.aerospike.client.cluster.Cluster.tend(Cluster.java:284)
	at com.aerospike.client.cluster.Cluster.run(Cluster.java:250)
	at java.lang.Thread.run(Thread.java:745)

1 INFO  AQL  - Node BB9A1969F732D02 172.31.30.81:3000 refresh failed: com.aerospike.client.AerospikeException$Parse: Error Code -2: Node name is empty
	at com.aerospike.client.cluster.Node.verifyNodeName(Node.java:111)
	at com.aerospike.client.cluster.Node.refresh(Node.java:91)
	at com.aerospike.client.cluster.Cluster.tend(Cluster.java:284)
	at com.aerospike.client.cluster.Cluster.run(Cluster.java:250)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by helipilot50** [comment]
Hi
This test case passes
```java
	@Test
	public void test() {
		for (int x = 0; x < 500; x++){
			Key key = new Key("test", "scanudf", "thing-"+x);
			this.client.put(null, key, new Bin("num", x + 100));
		}
		result = aql2.executeImmediate("set LUA_USERPATH 'user_udf'\n"
				+ "EXECUTE scanudf.time(0, 7500) ON test.scanudf");
		assertTrue(result.resultCode == ResultCode.OK);

	}
```
You appear to have a problem connecting to your cluster
